[package]
name = "vexy-json-serde"
version = "1.0.14"
edition = "2021"


[lib]
path = "src/lib.rs"


[dependencies.vexy-json-core]
path = "../core"
features = [ "serde" ]


[dependencies.serde]
version = "1.0"
features = [ "derive" ]


[features]
serde = [ ]
