site_name: Vexy JSON Documentation
site_url: https://vexyart.github.io/vexy-json
site_description: A forgiving JSON parser for Rust - Complete Documentation
repo_url: https://github.com/vexyart/vexy-json
repo_name: vexyart/vexy-json

docs_dir: md
site_dir: ../docs
use_directory_urls: true

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.select
    - content.tabs.link

plugins:
  - search:
      lang: en
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - Core Features: core-features.md
  - API Reference: api-reference.md
  - Language Bindings: language-bindings.md
  - Advanced Usage: advanced-usage.md
  - Performance Guide: performance-guide.md
  - Troubleshooting: troubleshooting.md
  - Contributing: contributing.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vexyart/vexy-json
    - icon: fontawesome/brands/rust
      link: https://crates.io/crates/vexy-json

extra_css:
  - stylesheets/extra.css