---
# Site metadata for SEO
author:
  name: Fontlab Ltd. dba Vexy Co
  url: https://vexy.art/
aux_links:
  View on GitHub:
    - https://github.com/vexyart/vexy-json
back_to_top: true
back_to_top_text: Back to top
baseurl: /vexy-json
# Collections
collections:
  pages:
    output: true
    permalink: /:name/
color_scheme: dark
defaults:
  - scope:
      path: ''
      type: pages
    values:
      layout: page
  - scope:
      path: pkg
    values:
      layout: none
description: Lenieng and tolerant JSON parser in Rust
enable_copy_code_button: true
exclude:
  - _build.sh
  - _serve.sh
  - '*.erb'
  - '*.gemspec'
  - '*.orig'
  - '*.sh'
  - '**/gems/jekyll-*/lib/site_template/_posts/*'
  - '**/site_template/**/*'
  - dev/**/*
  - Gemfile
  - Gemfile.lock
  - internal/**/*
  - node_modules/
  - package-lock.json
  - package.json
  - postcss.config.js
  - tailwind.config.js
footer_content: Copyright &copy; 2025 Vexy Co. MIT License.
github:
  repository_url: https://github.com/vexyart/vexy-json
highlighter: rouge
# Include WASM and tool files in build
include:
  - pkg
  - demo.html
  - tool.html
  - assets
incremental: false
# Development configuration
livereload: true
# Build settings
markdown: kramdown
# External navigation links will be removed from here as just-the-docs handles them in the content
# Plugin configuration
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-optional-front-matter
  - jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs
# Repository information
repository: vexyart/vexy-json 
# Performance and caching
sass:
  style: compressed
search:
  button: false
  heading_level: 2
  preview_words_after: 3
  preview_words_before: 3
  previews: 2
  rel_url: true
  tokenizer_separator: /[\s\-/]+/
# Just-the-docs theme configuration
search_enabled: true
# Social and sharing
social:
  - icon: github
    name: GitHub
    url: https://github.com/vexyart/vexy-json
# WASM and static file configuration
# Ensure proper MIME types for WebAssembly files
static_files:
  - /pkg/*.wasm
  - /pkg/*.js
  - /assets/**/*
# Site configuration for vexy-json documentation
title: Vexy JSON
url: https://vexyart.github.io/vexy-json
# MIME type handling for GitHub Pages
# Note: GitHub Pages automatically serves .wasm files with application/wasm MIME type
