name: Build & deploy MkDocs

on:
  push:
    branches: [main]
    paths:
      - 'docs-src/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  workflow_dispatch:

permissions:
  contents: write      # allow committing built site
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with: 
          python-version: '3.12'
      
      - name: Install dependencies
        run: |
          pip install \
            mkdocs-material \
            mkdocs-awesome-nav \
            mkdocs-nav-weight
      
      - name: Build MkDocs site
        run: mkdocs build --strict --config-file mkdocs.yml --site-dir docs
      
      - name: Add .nojekyll file
        run: touch docs/.nojekyll      # bypass GH Pages Jekyll
      
      - name: Commit & push to main/docs
        run: |
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git add docs
          git commit -m "docs: automated MkDocs build 📚" || echo "No changes"
          git push
